# Generated by Django 4.2.15 on 2024-09-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('author', models.CharField()),
                ('genre', models.CharField()),
                ('rating', models.IntegerField()),
                ('recommend', models.BooleanField()),
                ('notes', models.TextField(max_length=200)),
                ('read', models.BooleanField()),
                ('image', models.FileField(upload_to='')),
                ('image_date', models.BinaryField(null=True)),
            ],
        ),
    ]
