# Generated by Django 4.2.15 on 2024-09-05 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_image_date_books_image_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
