# Generated by Django 4.2.15 on 2024-09-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_books_book'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (0, 5))), name='book_rating_range'),
        ),
    ]
