# Generated by Django 4.2.15 on 2024-09-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_image_alter_book_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='daisies.webp', upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='recommend',
            field=models.BooleanField(null=True),
        ),
    ]
