# Generated by Django 4.2.15 on 2024-09-12 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_alter_book_image_alter_book_image_data_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='book_rating_range',
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (0, 5))), name='book_rating_range', violation_error_message='Please rate 0-5'),
        ),
    ]
