# Generated by Django 4.2.15 on 2024-09-17 23:35

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_profile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='book_rating_range',
        ),
        migrations.AddField(
            model_name='book',
            name='bookshelf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='book',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='text_color',
            field=colorfield.fields.ColorField(default='000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Not read'), (1, 'Hated it'), (2, 'Didnt like'), (3, 'It was okay'), (4, 'Liked it'), (5, 'Loved it')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='recommend',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
