# Generated by Django 4.2.15 on 2024-09-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_book_rating_range_book_bookshelf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Not read'), (1, 'Hated it'), (2, 'Didnt like'), (3, 'It was okay'), (4, 'Liked it'), (5, 'Loved it')], null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
