# Generated by Django 4.2.15 on 2024-09-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='position',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(choices=[(0, 'not read'), (1, 'hated it'), (2, 'disliked it'), (3, 'indifferent'), (4, 'liked it'), (5, 'loved it')], default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='recommend',
            field=models.BooleanField(null=True),
        ),
    ]
