# Generated by Django 4.2.15 on 2024-09-18 23:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_position_alter_book_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=colorfield.fields.ColorField(default='000000', image_field=None, max_length=25, samples=None),
        ),
    ]
