# Generated by Django 4.2.15 on 2024-09-21 16:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0016_alter_book_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('user', 'position')},
        ),
    ]
