# Generated by Django 4.2.15 on 2024-09-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='book',
            name='position',
            field=models.IntegerField(blank=True, choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')], null=True),
        ),
    ]
