# Generated by Django 4.2.15 on 2024-09-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_profile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
