# Generated by Django 4.2.15 on 2024-10-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_profile_description_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ispublic',
            field=models.BooleanField(default=True),
        ),
    ]
